"""add description to Account

Revision ID: 3f3c8995a49e
Revises: 8ca13f7edb61
Create Date: 2020-08-20 02:03:20.926146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3c8995a49e'
down_revision = '8ca13f7edb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('description', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'description')
    # ### end Alembic commands ###
